<script src="<?= base_url(); ?>assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="<?= base_url(); ?>assets/vendor/stepper/js/bs-stepper.min.js"></script>
<script src="<?= base_url(); ?>assets/vendor/purecounterjs/dist/purecounter_vanilla.js"></script>
<script src="<?= base_url(); ?>assets/vendor/apexcharts/js/apexcharts.min.js"></script>
<script src="<?= base_url(); ?>assets/vendor/overlay-scrollbar/js/overlayscrollbars.min.js"></script>
<script src="<?= base_url(); ?>assets/vendor/glightbox/js/glightbox.js"></script>
<script src="<?= base_url(); ?>assets/vendor/choices/js/choices.min.js"></script>
<script src="<?= base_url(); ?>assets/vendor/aos/aos.js"></script>
<script src="<?= base_url(); ?>assets/js/functions.js"></script>